### ISSUE TITLE
Hamburger icon related

### ISSUE THREAD

**Issue by Lakszy** [AmolShelke2/personal-portfolio#1]
When someone clicks on the content of hamburger the popup still remains on the screen
It can be fixed using useState. 
Simply 
onClick setNav=!setNav

The variable name may vary.

**Comment by AmolShelke2** [comment]
Hey @Lakszy , Thanks for this issue, I will fix it as soon as possible, If you wanna contribute to this you can also create a pull request I would appreciate it
